export {default as Blog } from './blog/blog'
export {default as Features } from './features/features'
export {default as Header } from './header/header'
export {default as  Possible } from './possiblites/possible'
export {default as Whatgpt } from './what-gpt/what-gpt'
export {default as Footer } from './footer/footer'